export const GET_WEATHER_DATA = "GET_WEATHER_DATA";
export const CHANGE_UNIT = "CHANGE_UNIT";
export const SET_SELECTED_CARD = "SET_SELECTED_CARD";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

export const GO_NEXT_PAGE = "GO_NEXT_PAGE";
export const GO_PREVIOUS_PAGE = "GO_PREVIOUS_PAGE";
export const SET_WEATHER_CARD_AMOUNT = "SET_WEATHER_CARD_AMOUNT";
